substitutions:
  _IMAGE_NAME: your-image-name
  _SERVICE_NAME: your-service-name
  _REGION: your-region
  _GCS_BUCKET: your-gcs-bucket
  _SERVICE_ACCOUNT: your-service@your-project.iam.gserviceaccount.com

steps:
  # Build the Docker image, cached
  - name: "gcr.io/kaniko-project/executor:latest"
    args: 
      - "--destination=gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
      - "--cache=true"
      - "--cache-ttl=6h"

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE_NAME} --image gcr.io/$PROJECT_ID/${_IMAGE_NAME} \
           --region ${_REGION} \
           --platform managed \
           --allow-unauthenticated \
           --memory 1Gi \
           --cpu 1 \
           --max-instances 2 \
           --service-account ${_SERVICE_ACCOUNT} \
           --update-env-vars OPENAI_API_KEY=$$OPENAI_API_KEY,GCS_BUCKET=${_GCS_BUCKET}
    secretEnv: ["OPENAI_API_KEY"]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
    env: OPENAI_API_KEY