substitutions:
  _IMAGE_NAME: your-image-name

steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/prebuild/${_IMAGE_NAME}", "."]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/prebuild/${_IMAGE_NAME}"]
